keybinding:
  universal:
    appendNewline: "<tab>"
  commits:
    moveDownCommit: "<f1>" # move commit down one
    moveUpCommit: "<f2>" # move commit up one
os:
  edit: "nvim {{filename}}"
customCommands:
  - key: "M"
    prompts:
      - type: "menu"
        title: "Select Option"
        options:
          - name: "Squash"
            description: "Merge Squash"
            value: "--squash"
          - name: "FastForward"
            description: "Merge FastForward"
            value: "--ff"
          - name: "No-FastForward"
            description: "Merge FastForward"
            value: "--no-ff"
    command: "git merge {{index .PromptResponses 0}} {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Merge Squash"
  - key: "<f9>"
    context: "files"
    command: "git checkout --ours  -- {{.SelectedPath}}"
    description: "Merge ours(HEAD)"
  - key: "<f10>"
    context: "files"
    command: "git checkout --theirs -- {{.SelectedPath}}"
    description: "Merge theirs"
